#spring.application.name=demo
server:
  port: 80

spring:
  application:
    name: demo

  thymeleaf:
    cache: false

  #schema.sql 과 data.sql 관리 가능 ( always|never )
  sql:
    init:
      mode: never

  # /ccc/**/ddd 사용시 ** 허용
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

