# frontend-service
apiVersion: v1
kind: Service
metadata:
  name: ykk-frontend-service
  namespace: ykk
spec: 
  selector:
    app: ykk-frontend      # Frontend Pod와 연결
  ports:
    - port: 80             # Service 포트
      targetPort: 80       # Frontend Pod 포트
      nodePort: 30080      # 외부 접속 포트
  type: NodePort           # 브라우저에서 외부 접속 가능