# 02-mysql.yaml

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ykk
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "1234"
  MYSQL_USER: "ykkuser"
  MYSQL_PASSWORD: "ykk123"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-node1
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data/mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: ykk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: ykk
spec:
  selector:
    app: ykk-mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ykk-mysql
  namespace: ykk
spec:
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: ykk-mysql
  template:
    metadata:
      labels:
        app: ykk-mysql
    spec:
      nodeName: node1
      containers:
        - name: mysql
          image: mysql:8.3
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: ykk-config
                  key: DB_NAME

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD

          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc