#spring.application.name=demo
server:
  port: 8080

spring:
  application:
    name: YKK_BACKEND

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
 #   url: ${DB_URL:jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false}
 #   username: root
 #   password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true

  #schema.sql 과 data.sql 관리 가능 ( always|never )
  sql:
    init:
      mode: always
